name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  release:
    types: [published]
  workflow_dispatch:  # Manual trigger

permissions:
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: List files
      run: |
        pwd
        ls -la
        ls -la IP5100/
    - name: Build package
      run: |
        python -m build
        ls -la dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1 